BEGIN;

-- One logical PostgreSQL history for Netsons and AWS. IDs are generated by application services.
CREATE TABLE accounts (
  id uuid PRIMARY KEY,
  primary_email text NOT NULL,
  email_verified_at timestamptz,
  status text NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
  terms_accepted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (length(primary_email) BETWEEN 3 AND 320)
);
CREATE UNIQUE INDEX accounts_primary_email_ci_unique ON accounts (lower(primary_email));

CREATE TABLE account_identities (
  id uuid PRIMARY KEY,
  account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
  provider text NOT NULL CHECK (provider IN ('PASSWORD', 'GOOGLE')),
  provider_subject text NOT NULL,
  email text NOT NULL,
  email_verified boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_subject),
  UNIQUE (account_id, provider)
);

CREATE TABLE seller_profiles (
  id uuid PRIMARY KEY,
  account_id uuid NOT NULL UNIQUE REFERENCES accounts(id) ON DELETE RESTRICT,
  display_name text NOT NULL CHECK (length(display_name) BETWEEN 1 AND 120),
  status text NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'SUSPENDED')),
  payout_status text NOT NULL CHECK (payout_status IN ('NOT_STARTED', 'IN_PROGRESS', 'RESTRICTED', 'ACTION_REQUIRED', 'READY', 'DISABLED')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE worker_devices (
  id uuid PRIMARY KEY,
  seller_profile_id uuid NOT NULL REFERENCES seller_profiles(id) ON DELETE RESTRICT,
  public_key text NOT NULL,
  name text NOT NULL CHECK (length(name) BETWEEN 1 AND 120),
  platform text NOT NULL CHECK (platform IN ('MACOS', 'LINUX', 'WINDOWS')),
  worker_version text NOT NULL,
  openclaw_version text,
  status text NOT NULL CHECK (status IN ('PAIRED', 'ONLINE', 'PAUSED', 'OFFLINE', 'REVOKED')),
  last_seen_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (status <> 'REVOKED' OR revoked_at IS NOT NULL)
);
CREATE INDEX worker_devices_seller_profile_idx ON worker_devices(seller_profile_id);

CREATE TABLE capabilities (
  id uuid PRIMARY KEY,
  seller_profile_id uuid NOT NULL REFERENCES seller_profiles(id) ON DELETE RESTRICT,
  slug text NOT NULL UNIQUE,
  name text NOT NULL CHECK (length(name) BETWEEN 1 AND 160),
  description text NOT NULL DEFAULT '',
  status text NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'PAUSED', 'SUSPENDED')),
  current_version_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX capabilities_seller_profile_idx ON capabilities(seller_profile_id);

CREATE TABLE capability_versions (
  id uuid PRIMARY KEY,
  capability_id uuid NOT NULL REFERENCES capabilities(id) ON DELETE RESTRICT,
  version_number integer NOT NULL CHECK (version_number > 0),
  publication_state text NOT NULL CHECK (publication_state IN ('DRAFT', 'PUBLISHED')),
  version_snapshot jsonb NOT NULL CHECK (jsonb_typeof(version_snapshot) = 'object'),
  worker_manifest_hash text NOT NULL CHECK (worker_manifest_hash ~ '^sha256:[a-f0-9]{64}$'),
  policy_validation_hash text CHECK (policy_validation_hash ~ '^sha256:[a-f0-9]{64}$'),
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (capability_id, version_number),
  UNIQUE (id, capability_id),
  CHECK ((publication_state = 'PUBLISHED') = (published_at IS NOT NULL AND policy_validation_hash IS NOT NULL))
);
ALTER TABLE capabilities ADD CONSTRAINT capabilities_current_version_fk
  FOREIGN KEY (current_version_id, id) REFERENCES capability_versions(id, capability_id) ON DELETE RESTRICT;

CREATE FUNCTION prevent_published_version_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.publication_state = 'PUBLISHED' THEN
    RAISE EXCEPTION 'Published capability versions are immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER capability_versions_immutable
  BEFORE UPDATE OR DELETE ON capability_versions
  FOR EACH ROW EXECUTE FUNCTION prevent_published_version_mutation();

CREATE TABLE jobs (
  id uuid PRIMARY KEY,
  buyer_account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
  capability_version_id uuid NOT NULL REFERENCES capability_versions(id) ON DELETE RESTRICT,
  worker_device_id uuid NOT NULL REFERENCES worker_devices(id) ON DELETE RESTRICT,
  status text NOT NULL CHECK (status IN (
    'CREATED', 'PAYMENT_RESERVED', 'QUEUED', 'WAITING_FOR_WORKER', 'DISPATCHED',
    'ACCEPTED', 'STARTING', 'RUNNING', 'UPLOADING_RESULT', 'CANCEL_REQUESTED',
    'COMPLETED', 'REJECTED', 'EXPIRED', 'CANCELLED', 'FAILED_STARTUP',
    'FAILED_POLICY', 'FAILED_EXECUTION', 'TIMED_OUT', 'WORKER_OFFLINE', 'RESULT_REJECTED'
  )),
  contract_snapshot jsonb NOT NULL CHECK (jsonb_typeof(contract_snapshot) = 'object'),
  payment_reservation_id uuid,
  result_manifest_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  CHECK (status NOT IN (
    'PAYMENT_RESERVED', 'QUEUED', 'WAITING_FOR_WORKER', 'DISPATCHED', 'ACCEPTED',
    'STARTING', 'RUNNING', 'UPLOADING_RESULT', 'CANCEL_REQUESTED', 'COMPLETED'
  ) OR payment_reservation_id IS NOT NULL),
  CHECK (status <> 'COMPLETED' OR (result_manifest_id IS NOT NULL AND completed_at IS NOT NULL))
);
CREATE INDEX jobs_buyer_created_idx ON jobs(buyer_account_id, created_at DESC);
CREATE INDEX jobs_version_idx ON jobs(capability_version_id);
CREATE INDEX jobs_worker_status_idx ON jobs(worker_device_id, status);

CREATE FUNCTION guard_job_snapshot_and_version() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE version_state text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    SELECT publication_state INTO version_state FROM capability_versions WHERE id = NEW.capability_version_id FOR SHARE;
    IF version_state IS DISTINCT FROM 'PUBLISHED' THEN
      RAISE EXCEPTION 'Jobs require a published capability version';
    END IF;
  ELSE
    IF NEW.contract_snapshot IS DISTINCT FROM OLD.contract_snapshot OR
       NEW.capability_version_id IS DISTINCT FROM OLD.capability_version_id OR
       NEW.buyer_account_id IS DISTINCT FROM OLD.buyer_account_id OR
       NEW.worker_device_id IS DISTINCT FROM OLD.worker_device_id THEN
      RAISE EXCEPTION 'Historical job contract and ownership are immutable';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER jobs_contract_immutable
  BEFORE INSERT OR UPDATE ON jobs
  FOR EACH ROW EXECUTE FUNCTION guard_job_snapshot_and_version();

CREATE TABLE job_transitions (
  id uuid PRIMARY KEY,
  job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE RESTRICT,
  sequence integer NOT NULL CHECK (sequence > 0),
  from_status text NOT NULL,
  to_status text NOT NULL,
  at timestamptz NOT NULL,
  actor text NOT NULL CHECK (actor IN ('BUYER', 'SELLER', 'CLOUD', 'WORKER', 'PAYMENT', 'SYSTEM')),
  reason text NOT NULL CHECK (length(reason) BETWEEN 1 AND 200),
  attempt_id uuid,
  correlation_id uuid NOT NULL,
  payment_reservation_id uuid,
  result_manifest_id uuid,
  UNIQUE (job_id, sequence),
  CHECK (to_status <> 'PAYMENT_RESERVED' OR (actor = 'PAYMENT' AND payment_reservation_id IS NOT NULL)),
  CHECK (to_status <> 'COMPLETED' OR (actor = 'CLOUD' AND result_manifest_id IS NOT NULL))
);
CREATE INDEX job_transitions_job_idx ON job_transitions(job_id, sequence);

CREATE FUNCTION prevent_transition_rewrite() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Job transitions are append-only';
END;
$$;
CREATE TRIGGER job_transitions_append_only
  BEFORE UPDATE OR DELETE ON job_transitions
  FOR EACH ROW EXECUTE FUNCTION prevent_transition_rewrite();

COMMIT;
