import Link from 'next/link';
import { MarketplaceHeader } from '../discover/marketplace-ui';
export default function MarketplaceTermsPage(){return <main className="site-shell market-shell"><MarketplaceHeader/>
  <article className="terms-page"><p className="eyebrow">MARKETPLACE USE TERMS · VERSION 1</p><h1>Clear terms for useful work.</h1><p>These marketplace use terms describe how a Kivro buyer purchases seller-hosted capabilities. You must explicitly accept this version before buying a job.</p>
    <h2>Purchases and credits</h2><p>A capability has a published fixed price shown before purchase. Kivro Credits must be available and reserved before a paid job can execute. A quote has an expiry and is rechecked when you confirm; a changed price, version, schedule or availability may require a new quote.</p>
    <h2>Execution and scheduling</h2><p>Jobs may run immediately, wait in a queue or start in a future eligible window. The displayed start time is an estimate unless explicitly stated otherwise. Seller availability, Worker health and capacity can change. A maximum wait or latest start shown in the quote bounds the wait; jobs that cannot start within that policy expire.</p>
    <h2>Cancellation and failed jobs</h2><p>Eligible cancellation before paid execution begins releases reserved credits. Once execution starts, the applicable job state and published cancellation rules determine whether cancellation is available. Failed or expired jobs follow the Kivro financial release and reconciliation policy. A Worker message alone does not decide whether seller earnings are due.</p>
    <h2>Your inputs and results</h2><p>Your inputs are provided to the selected seller capability within its declared permission boundary. File inputs and outputs are held in private Kivro-controlled storage. Completed results are available from your authenticated job page while retained. Result file expiry is shown on the job page. You may report a missing or problematic result from that page.</p>
    <h2>Reviews</h2><p>You may review only a completed paid job that you bought. One review may be submitted per job. Reviews must describe your own experience and must not disclose secrets or another person’s private information.</p>
    <p className="terms-version">Version 1 · Published 7 October 2026</p><Link href="/discover" className="primary-button">Explore capabilities</Link></article>
  <footer className="site-footer"><span>© 2026 Kivro</span><span>Marketplace use terms</span></footer></main>}
